name: Deploy main site and portal to GitHub Pages
on:
  push:
    branches: [ main ]
    paths:
      - 'src/App.tsx'
      - 'src/main.tsx'
      - 'src/pages/Home.tsx'
      - 'src/pages/OrderConfirmation.tsx'
      - 'src/components/TilausModal.tsx'
      - 'src/PortalApp.tsx'
      - 'src/portal-main.tsx'
      - 'src/pages/AdminPortal.tsx'
      - 'src/pages/Dashboard.tsx'
      - 'vite.config.ts'
      - 'vite-portal.config.ts'
      - 'index.html'
      - 'index-portal.html'
      - 'public/_redirects'
jobs:
  build-deploy-main:
    runs-on: ubuntu-latest
    permissions: { contents: write, pages: write, id-token: write }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
      - run: cp public/_redirects dist/_redirects
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git push origin --delete gh-pages || true
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true
          cname: omaverkkoturva.fi
          
  build-deploy-portal:
    runs-on: ubuntu-latest
    permissions: { contents: write, pages: write, id-token: write }
    needs: build-deploy-main
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npm run build:portal
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
      - run: echo "Portal build completed"
      - run: cp public/_redirects-portal dist-portal/_redirects
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist-portal
          publish_branch: gh-pages-portal
          force_orphan: true
          cname: portaali.omaverkkoturva.fi
          